name: Bug report
description: Report a reproducible bug
title: "bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

        If this is a security issue (auth bypass, token leak, file upload exploit, etc.), please follow SECURITY.md instead of filing a public issue.

  - type: dropdown
    id: component
    attributes:
      label: Affected component
      options:
        - Client (EchoHub.Client)
        - Server (EchoHub.Server)
        - Core/shared (EchoHub.Core)
        - Docs
        - CI
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
      placeholder: "When I..., I expected..., but ..."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Include minimal, numbered steps.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      description: Paste relevant logs (redact tokens/secrets).
      render: text

  - type: input
    id: version
    attributes:
      label: Version
      description: App version, commit SHA, or release tag.
      placeholder: v0.1.0

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, terminal, .NET SDK version.
      placeholder: |
        OS: Windows 11
        Terminal: Windows Terminal
        .NET SDK: 10.0.x

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: I searched existing issues and this is not a duplicate
          required: true
        - label: I removed sensitive info (tokens/keys) from logs
          required: true
